---
- name: Validate and setup dynamic hosts
  hosts: localhost  # Only runs on AWX server
  tasks:
    - name: Fail if no hosts provided
      fail:
        msg: "No hosts specified! Use the survey to enter target servers."
      when: runtime_servers == "unspecified"

    - name: Add dynamic hosts
      add_host:
        name: "{{ item }}"
        groups: apache_servers
        # Explicitly set connection vars
        ansible_connection: ssh
        ansible_user: "{{ runtime_user | default('vagrant') }}"
      loop: "{{ runtime_servers.split(',') }}"

- name: Install Apache on runtime hosts
  hosts: apache_servers  # Only runs on dynamically added hosts
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
